// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#ifndef TOTESTACKERNEW_H
#define TOTESTACKERNEW_H
#include "Commands/Subsystem.h"
#include "WPILib.h"
#include "StackerRelative.h"

/**
 *
 *
 * @author ExampleAuthor
 */
class ToteStackerNew: public Subsystem {
private:
	// It's desirable that everything possible under private except
	// for methods that implement subsystem capabilities
	CANTalon* toteLift;
	Solenoid* brake;
	DigitalInput* toteHall;
	StackerRelative m_relativePosition;
	bool m_resting;
	int m_offset;
	bool m_manual;
	bool m_justMan;
	int ComputeSetPoint();
public:
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

	// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	ToteStackerNew();
	void InitDefaultCommand();
	int GetPos();
	bool IsAtHome();
	void SetRelative(StackerRelative position);
	StackerRelative GetRelative();
	bool GetHall();
	void SetSpeed(double speed);
	void DriveToHome();
	void DriveToPoint();
	void DriveToPoint(int position);
	bool IsAtSetPoint();
	void ZeroTote();
	void SetResting(bool resting);
	void SetOffset(int offset);
	void SetManual(bool manual);
	bool GetManual();
	void SetJustManTote(bool justMan);
	bool GetJustManTote();

};

#endif
