// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#ifndef OI_H
#define OI_H

#include "WPILib.h"
#include "OIMap.h"
#include "InvertedIOButton.h"

class OI {
private:
	Joystick* m_sStick;
	Joystick* m_cStick;
	
	//Container Stacker
	JoystickButton* m_contControlMode;
	JoystickButton* m_contClaw;
	InvertedIOButton* m_contPlatform;
	InvertedIOButton* m_contUp;
	InvertedIOButton* m_contDown;

	//Tote Stacker
	JoystickButton* m_toteControlMode;
	InvertedIOButton* m_toteUp;
	InvertedIOButton* m_toteDown;
	InvertedIOButton* m_toteStep;
	InvertedIOButton* m_totePlatform;
	InvertedIOButton* m_totePickup;

	//Acquisition
	InvertedIOButton* m_acqOut;
	InvertedIOButton* m_acqIn;
	JoystickButton* m_acqPosition;

	//Drive
	JoystickButton* m_driveCenterDown;
	JoystickButton* m_driveCenterUp;

public:
	OI();
 
	double GetSingleY();
	double GetSingleX();
	double GetSingleTurn();
	int GetDial();
	int GetDialTote();
	bool GetAcqArms();
	bool GetClaw();
	bool GetAutoMan();
	bool GetAutoManTote();
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=PROTOTYPES

	// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=PROTOTYPES
};

#endif
