// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "SayHello.h"

SayHello::SayHello() {
	// Use requires() here to declare subsystem dependencies
	// eg. requires(chassis);SayHello
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	Requires(Robot::drive);
	// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	m_count = 0;
}

// Called just before this Command runs the first time
void SayHello::Initialize() {
	m_count = 0;
}

// Called repeatedly when this Command is scheduled to run
void SayHello::Execute() {
	m_count ++;
	SmartDashboard::PutNumber("Testing", m_count);
}

// Make this return true when this Command no longer needs to run execute()
bool SayHello::IsFinished() {
	return m_count > 1000;
}

// Called once after isFinished returns true
void SayHello::End() {
	
}

// Called when another command which requires one or more of the same
// subsystems is scheduled to run
void SayHello::Interrupted() {

}
