// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#ifndef JOYSTICKAUTODRIVE_H
#define JOYSTICKAUTODRIVE_H

#define INCH 55;

#include "Commands/Subsystem.h"
#include "../../Robot.h"

/**
 *
 *
 * @author ExampleAuthor
 */
class JoystickAutoDrive: public Command {
public:
	JoystickAutoDrive(double forwardSpeed, double sideSpeed, double , double leftDistance, double rightDistance, double sideDistance);
	virtual void Initialize();
	virtual void Execute();
	virtual bool IsFinished();
	virtual void End();
	virtual void Interrupted();

	double m_forwardSpeed;
	double m_sideSpeed;
	double m_turnSpeed;
	double m_forwardDistance;
	double m_sideDistance;
	double m_turnDegrees;
	double m_startLeft;
	double m_startRight;
	double m_startSide;
	double m_startDegrees;
};

#endif
