// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "OI.h"

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES
#include "SmartDashboard/SmartDashboard.h"
#include "Commands/AutonomousCommand.h"
#include "Commands/BrakeOff.h"
#include "Commands/BrakeOn.h"
#include "Commands/CloseClaw.h"
#include "Commands/DropTotes.h"
#include "Commands/ExtendArms.h"
#include "Commands/JoystickAutoDrive.h"
#include "Commands/JoystickHDrive.h"
#include "Commands/LowerHWheel.h"
#include "Commands/OpenClaw.h"
#include "Commands/RaiseHWheel.h"
#include "Commands/ResetClaw.h"
#include "Commands/ResetTote.h"
#include "Commands/RetractArms.h"
#include "Commands/RetractWings.h"
#include "Commands/SetClawPos.h"
#include "Commands/StopWheels.h"
#include "Commands/ToteIntake.h"
#include "Commands/ToteOutput.h"
#include "Commands/ToteSetPos.h"

// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES

OI::OI() {
	// Process operator interface input here.
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS

     

        // SmartDashboard Buttons
	SmartDashboard::PutData("Autonomous Command", new AutonomousCommand());

	SmartDashboard::PutData("ToteIntake", new ToteIntake());

	SmartDashboard::PutData("ToteOutput", new ToteOutput());

	SmartDashboard::PutData("ExtendArms", new ExtendArms());

	SmartDashboard::PutData("RetractArms", new RetractArms());

	SmartDashboard::PutData("StopWheels", new StopWheels());

	SmartDashboard::PutData("JoystickHDrive", new JoystickHDrive());

	SmartDashboard::PutData("JoystickAutoDrive", new JoystickAutoDrive());

	SmartDashboard::PutData("RetractWings", new RetractWings());

	SmartDashboard::PutData("LowerHWheel", new LowerHWheel());

	SmartDashboard::PutData("RaiseHWheel", new RaiseHWheel());

	SmartDashboard::PutData("ResetClaw", new ResetClaw());

	SmartDashboard::PutData("CloseClaw", new CloseClaw());

	SmartDashboard::PutData("OpenClaw", new OpenClaw());

	SmartDashboard::PutData("SetClawPos", new SetClawPos());

	SmartDashboard::PutData("ResetTote", new ResetTote());

	SmartDashboard::PutData("DropTotes", new DropTotes());

	SmartDashboard::PutData("BrakeOn", new BrakeOn());

	SmartDashboard::PutData("BrakeOff", new BrakeOff());

	SmartDashboard::PutData("ToteSetPos", new ToteSetPos());

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
}

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS

// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS
