// RobotBuilder Version: 1.5 ♥♥♥♥♥
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#ifndef ROBOTMAP_H
#define ROBOTMAP_H
#include "WPILib.h"

/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
class RobotMap {
public:
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	static CANTalon* drivelDrive;
	static CANTalon* driverDrive;
	static CANTalon* drivecDrive;
	static Solenoid* drivelowerWheel;
	static Ultrasonic* drivelSonic;
	static Ultrasonic* driverSonic;
	static AnalogInput* drivelIR;
	static AnalogInput* driverIR;
	static Talon* acquisitionlAcquisition;
	static Talon* acquisitionrAcquisition;
	static Solenoid* acquisitionacqArm;
	static DigitalInput* acquisitiontoteSensor;
	static CANTalon* toteStackertoteLift;
	static Solenoid* toteStackerbrake;
	static DigitalInput* toteStackertoteHome;
	static CANTalon* containerStackercontainerLift;
	static Solenoid* containerStackerclaw;
	static DigitalInput* containerStackercontainerHome;
	static AnalogInput* containerStackerclawIR;
	static Victor* wingswingRetracter;
	// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

	static void init();

	/* Naming scheme for ports:
	 * "Subsystem_Type_Function"
	 *
	 * Subsystem:
	 * ACQ - Acquisition
	 * DRV - Drive
	 * RBT - No subsystem
	 * TST - Tote stacker
	 * CST - Container stacker
	 * WNG - Wings
	 *
	 * Type:
	 * ANA - Analog Channel
	 * MTR - Motor
	 * SOL - Solenoid
	 * ENC - Encoder
	 * POT - Potentiometer
	 * CNT - Counter
	 * PRS - Pressure switch
	 * CMP - Compressor
	 * DIN - Digital input
	 * ULT - Ultrasonic
	 */

//Drive
#define DRV_MTR_LEFT 8 //beware: dummy(~ish~) values ahead
#define DRV_MTR_RIGHT 5
#define DRV_MTR_CENTER 4
#define DRV_SOL_CNTR_SUSP 0, 3
#define DRV_ULT_LEFTD 6, 7
#define DRV_ULT_RIGHTD 8, 9
#define DRV_ANA_LEFT 0
#define DRV_ANA_RIGHT 1

//Acquisition
#define ACQ_MTR_LEFT 2
#define ACQ_MTR_RIGHT 3
#define ACQ_SOL_EXTEND 0, 2
#define ACQ_DIN_TOTE_SENSE 4

//Tote stacker
#define TST_MTR_LIFT 7
#define TST_SOL_BRAKE 0, 1
#define TST_DIN_HOME 0

//Container stacker
#define CST_MTR_LIFT 6
#define CST_SOL_CLAW 0, 0
#define CST_DIN_HOME 3
#define CST_ANA_IR 2

//Wing
#define WNG_MTR_RET 9
};
#endif
