// RobotBuilder Version: 1.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

#include "ArmLower.h"

#define TIME_THRESH_1 .275 //TODO: Replace potential dummy value
#define TIME_THRESH_2 .625 //TODO: Replace potential dummy value
#define TIME_THRESH_END .7 //TODO: Replace potential dummy value

ArmLower::ArmLower() {
	// Use requires() here to declare subsystem dependencies
	// eg. requires(chassis);
	Requires(Robot::acquisition);
	SetInterruptible(false);
}

// Called just before this Command runs the first time
void ArmLower::Initialize() {
	lowerTime.Start();
	lowerTime.Reset();
}

// Called repeatedly when this Command is scheduled to run
void ArmLower::Execute() {
	if(lowerTime.Get() < TIME_THRESH_1)			
		Robot::acquisition->SetArm(1);			// Go down partway
	else if (lowerTime.Get() < TIME_THRESH_2)	
		Robot::acquisition->SetArm(0);			// Reverse direction to slow down
	else 										
		Robot::acquisition->SetArm(1);			// Go down the rest of the way
}

// Make this return true when this Command no longer needs to run execute()
bool ArmLower::IsFinished() {
	return lowerTime.Get() > TIME_THRESH_END;
}

// Called once after isFinished returns true
void ArmLower::End() {
	
}

// Called when another command which requires one or more of the same
// subsystems is scheduled to run
void ArmLower::Interrupted() {

}
