// RobotBuilder Version: 1.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

#include "ArmRaise.h"

#define TIME_THRESH_1 .8 	//TODO: Replace potential dummy value
#define TIME_THRESH_2 1  	//TODO: Replace potential dummy value
#define TIME_THRESH_END 1.1 //TODO: Replace potential dummy value 

ArmRaise::ArmRaise() {
	// Use requires() here to declare subsystem dependencies
	// eg. requires(chassis);
	Requires(Robot::acquisition);
	SetInterruptible(false);
}

// Called just before this Command runs the first time
void ArmRaise::Initialize() {
	raiseTime.Start();
	raiseTime.Reset();
}

// Called repeatedly when this Command is scheduled to run
void ArmRaise::Execute() {
	if(raiseTime.Get() < TIME_THRESH_1)			
		Robot::acquisition->SetArm(0);			// Go up partway
	else if (raiseTime.Get() < TIME_THRESH_2)	
		Robot::acquisition->SetArm(1);			// Reverse direction to slow down
	else 										
		Robot::acquisition->SetArm(0);			// Go up the rest of the way
}

// Make this return true when this Command no longer needs to run execute()
bool ArmRaise::IsFinished() {
	return raiseTime.Get() > TIME_THRESH_END;
}

// Called once after isFinished returns true
void ArmRaise::End() {
	
}

// Called when another command which requires one or more of the same
// subsystems is scheduled to run
void ArmRaise::Interrupted() {

}
