// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "DropTotes.h"
#include "ToteSetPos.h"

DropTotes::DropTotes() {
	// Use requires() here to declare subsystem dependencies
	// eg. requires(chassis);
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
//	Requires(Robot::toteStacker);
	// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	m_timer = new Timer();
}

// Called just before this Command runs the first time
void DropTotes::Initialize() {
	m_timer->Reset();
	m_timer->Start();
}

// Called repeatedly when this Command is scheduled to run
void DropTotes::Execute() {
//	Robot::toteStacker->SetDrop(m_timer->HasPeriodPassed(1)); //Time in seconds
}

// Make this return true when this Command no longer needs to run execute()
bool DropTotes::IsFinished() {
	return false;
}

// Called once after isFinished returns true
void DropTotes::End() {
//	Robot::toteStacker->SetDrop(false);
}

// Called when another command which requires one or more of the same
// subsystems is scheduled to run
void DropTotes::Interrupted() {
//	Robot::toteStacker->SetDrop(false);
}
