// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "DropTotes.h"
#include "ToteSetPos.h"
#include "../../Subsystems/StackerActions.h"

DropTotes::DropTotes() {
	// Use requires() here to declare subsystem dependencies
	// eg. requires(chassis);
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	Requires(Robot::toteStacker);
	// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	m_timer = new Timer();
	m_finished = false;
}

// Called just before this Command runs the first time
void DropTotes::Initialize() {
	m_timer->Start();
	m_timer->Reset();
}

// Called repeatedly when this Command is scheduled to run
void DropTotes::Execute() {
	if(m_timer->Get() > 1 && !m_finished) {
		Command* command = new ToteSetPos(StackerActions::DROP_TOTES);
		command->Start();
	}
}

// Make this return true when this Command no longer needs to run execute()
bool DropTotes::IsFinished() {
	return m_finished;
}

// Called once after isFinished returns true
void DropTotes::End() {

}

// Called when another command which requires one or more of the same
// subsystems is scheduled to run
void DropTotes::Interrupted() {

}
