// RobotBuilder Version: 0.0.2
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.
#ifndef SHOOTER_H
#define SHOOTER_H
#include "Commands/Subsystem.h"
#include "WPILib.h"
#include "Arm.h"
/**
 *
 *
 * @author ExampleAuthor
 */
class Shooter: public Subsystem {
private:
	// It's desirable that everything possible under private except
	// for methods that implement subsystem capabilities
	CANJaguar* spinner;
	Timer m_time;
	double m_defaultSpeed;
	double m_speed;
	bool m_bEnabled;
public:
	Shooter();
	void InitDefaultCommand();
	void Start();
	void Stop();
	void SetSpeed(double speed);
	double GetSpeed();
	bool IsEnabled();
	double GetRunTime();
	double GetDefaultSpeed();
	void SetArmState(Arm::State state);
};
#endif
