// RobotBuilder Version: 1.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#ifndef DRIVE_H
#define DRIVE_H

#include "Commands/Subsystem.h"
#include "WPILib.h"
/**
 *
 *
 * @author ExampleAuthor
 */
class Drive: public Subsystem {
private:
	// It's desirable that everything possible under private except
	// for methods that implement subsystem capabilities
	CANJaguar* left1;
	CANJaguar* left2;
	CANJaguar* left3;
	CANJaguar* right1;
	CANJaguar* right2;
	CANJaguar* right3;
	Solenoid* shift;
public:
	
	Drive();
	void InitDefaultCommand();
	void TankDrive(double lSpeed, double rSpeed);
	void Shift(bool isHigh);
};

#endif
