// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.




#include "Drive.h"
#include "../RobotMap.h"
#include "../Commands/JoystickHDrive.h"
#include "math.h"
// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES
// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES

Drive::Drive() : Subsystem("Drive") {
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	leftDrive = RobotMap::driveLeftDrive;
	rightDrive = RobotMap::driveRightDrive;
	centerDrive = RobotMap::driveCenterDrive;
	lowerWheel = RobotMap::drivelowerWheel;
	FullSpeed = true;
	// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
}
    
void Drive::InitDefaultCommand() {
	// Set the default command for a subsystem here.
	//SetDefaultCommand(new MySpecialCommand());
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
	// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
	SetDefaultCommand(new JoystickHDrive());
}

void Drive::HDrive(double forwardSpeed, double sideSpeed, double turnSpeed) {
	if(!FullSpeed) {
		forwardSpeed /= 2;
		sideSpeed /= 2;
		turnSpeed /= 2;
	}
	double leftSpeed = forwardSpeed + turnSpeed;
	double rightSpeed = forwardSpeed - turnSpeed;
	if(leftSpeed > 1) leftSpeed = 1;
	if(leftSpeed < -1) leftSpeed = -1;
	if(rightSpeed > 1) rightSpeed = 1;
	if(rightSpeed < -1) rightSpeed = -1;
	if(FullSpeed) {
		leftSpeed *= fabs(leftSpeed);
		rightSpeed *= fabs(rightSpeed);
		sideSpeed *= fabs(sideSpeed);
	}
	leftDrive->Set(-leftSpeed);
	rightDrive->Set(rightSpeed);
	centerDrive->Set(-sideSpeed);
}

void Drive::ToggleSpeed(){
	FullSpeed = !FullSpeed;
}

void Drive::SetCenterWheel(bool down) {
	lowerWheel->Set(down);
}

// Put methods for controlling this subsystem
// here. Call these from Commands.

