
#ifndef DRIVE_H
#define DRIVE_H
#include "Commands/Subsystem.h"
#include "WPILib.h"

#include "../DriveMotorOutput.h"

/**
 *
 *
 * @author ExampleAuthor
 */
class Drive: public Subsystem {
private:
	// It's desirable that everything possible under private except
	// for methods that implement subsystem capabilities
	DriveMotorOutput* lDrive;
	DriveMotorOutput* rDrive;
public:
	// The following variables are automatically assigned by
	// robotbuilder and will be updated the next time you export to
	// Java from robot builder. Do not put any code or make any change
	// in the following block or it will be lost on an update. To
	// prevent this subsystem from being automatically updated, delete
	// the following line.
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	Solenoid* shifter;
	Encoder* rEnc;
	Encoder* lEnc;
	CANJaguar* rJagB;
	CANJaguar* rJagA;
	CANJaguar* lJagB;
	CANJaguar* lJagA;
	// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	Drive();
	void InitDefaultCommand();
	
	void TankDrive(double left, double right);
};

#endif
