#include "Drive.h"
#include "../Robotmap.h"
#include "../Commands/JoystickDrive.h"
#include "../LiveDisable.h"

Drive::Drive() : Subsystem("Drive") {
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	shifter = RobotMap::DRIVE_SHIFTER;
	rEnc = RobotMap::DRIVE_RENC;
	lEnc = RobotMap::DRIVE_LENC;
	rJagB = RobotMap::DRIVE_RJAGB;
	rJagA = RobotMap::DRIVE_RJAGA;
	lJagB = RobotMap::DRIVE_LJAGB;
	lJagA = RobotMap::DRIVE_LJAGA;
	// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	
	lDrive = new DriveMotorOutput(lJagA, lJagB, lEnc);
	LiveWindow::GetInstance()->AddActuator("Drive", "lDrive", lDrive);
	rDrive = new DriveMotorOutput(rJagA, rJagB, rEnc);
	LiveWindow::GetInstance()->AddActuator("Drive", "rDrive", rDrive);
	
	// Magic to stop commands from running while in LiveWindow mode
	LiveWindow::GetInstance()->AddSensor("Drive", "FAKE", new LiveDisable(this));
}

void Drive::InitDefaultCommand() {
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
	SetDefaultCommand(new JoystickDrive());
	// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
}

void Drive::TankDrive(double left, double right)
{
	lDrive->Set(left);
	rDrive->Set(-right);
}
