// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "ForwardAutoDrive.h"

ForwardAutoDrive::ForwardAutoDrive(double inches, double speed) :
			m_inches(inches),
			m_speed(speed)
{
	// Use requires() here to declare subsystem dependencies
	// eg. requires(chassis);
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	Requires(Robot::drive);
	// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	m_ticks = m_inches * INCH;
}

// Called just before this Command runs the first time
void ForwardAutoDrive::Initialize() {
	m_startTicksRight = Robot::drive->GetRightEnc();
	m_startTicksLeft = Robot::drive->GetLeftEnc();
	if(m_ticks < 0) {
		m_speed *= -1;
	}
}

// Called repeatedly when this Command is scheduled to run
void ForwardAutoDrive::Execute() {

	Robot::drive->HDrive(m_speed,0,0);
}

// Make this return true when this Command no longer needs to run execute()
bool ForwardAutoDrive::IsFinished() {
	return (fabs(Robot::drive->GetRightEnc() - m_startTicksRight) > fabs(m_ticks) && fabs(Robot::drive->GetLeftEnc() - m_startTicksLeft) > fabs(m_ticks));
}

// Called once after isFinished returns true
void ForwardAutoDrive::End() {
	Robot::drive->HDrive(0,0,0);
}

// Called when another command which requires one or more of the same
// subsystems is scheduled to run
void ForwardAutoDrive::Interrupted() {
	Robot::drive->HDrive(0,0,0);
}
