// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "TurnAutoDrive.h"

TurnAutoDrive::TurnAutoDrive(double degrees, double speed) :
				m_degrees(degrees),
				m_speed(speed)

{
	// Use requires() here to declare subsystem dependencies
	// eg. requires(chassis);
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	Requires(Robot::drive);
	// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	m_ticks = degrees * DEGREE;
}

// Called just before this Command runs the first time
void TurnAutoDrive::Initialize() {
	m_startTicksLeft = Robot::drive->GetLeftEnc();
	m_startTicksRight = Robot::drive->GetRightEnc();
	if(m_ticks < 0) {
		m_speed *= -1;
	}

}

// Called repeatedly when this Command is scheduled to run
void TurnAutoDrive::Execute() {
	Robot::drive->HDrive(0,0,m_speed);
}

// Make this return true when this Command no longer needs to run execute()
bool TurnAutoDrive::IsFinished() {
	return (fabs(m_startTicksLeft - Robot::drive->GetLeftEnc()) > fabs(m_ticks) && fabs(m_startTicksRight - Robot::drive->GetRightEnc()) > fabs(m_ticks));
}

// Called once after isFinished returns true
void TurnAutoDrive::End() {
	Robot::drive->HDrive(0,0,0);
}

// Called when another command which requires one or more of the same
// subsystems is scheduled to run
void TurnAutoDrive::Interrupted() {
	Robot::drive->HDrive(0,0,0);
}
