// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#ifndef TurnAutoDrive_H
#define TurnAutoDrive_H

#define DEGREE 100
#include "Commands/Subsystem.h"
#include "../../Robot.h"

/**
 *
 *
 * @author ExampleAuthor
 */
class TurnAutoDrive: public Command {
public:
	TurnAutoDrive(double degrees, double speed);
	virtual void Initialize();
	virtual void Execute();
	virtual bool IsFinished();
	virtual void End();
	virtual void Interrupted();

	double m_degrees;
	double m_speed;
	int m_ticks;
	int m_startTicksLeft;
	int m_startTicksRight;
};

#endif
