// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#ifndef CONTAINERSTACKER_H
#define CONTAINERSTACKER_H
#include "Commands/Subsystem.h"
#include "WPILib.h"

/**
 *
 *
 * @author ExampleAuthor
 */
class ContainerStacker: public Subsystem {
private:
	// It's desirable that everything possible under private except
	// for methods that implement subsystem capabilities
	CANTalon* containerLift;
	Solenoid* claw;
	DigitalInput* containerHall;
	int m_targetHeight;
	bool m_standingMode;
	bool m_platform;
	bool m_manualControl;
	bool m_justMan;
	void CheckSensors();
public:
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

	// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	ContainerStacker();
	void InitDefaultCommand();
	void SetClaw(bool closed);
	void DriveToPoint();
	int GetTargetHeight();
	void SetTargetHeight(int height);
	bool IsAtHome();
	void SetStanding(bool standing);
	bool GetStanding();
	void SetPlatform(bool platform);
	bool GetPlatform();
	bool GetManual();
	void SetControlMode(bool manual);
	double GetCurrentPos();
	bool GetHall();
	void SetSpeed(double speed);
	int CalculatePos();
	void RunToHome();
	void DriveToPoint(int point);
	void ZeroContainer();
	void SetJustMan(bool justMan);
	bool GetJustMan();
};

#endif
