// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#ifndef SERIALSENSOR_H
#define SERIALSENSOR_H
#include "Commands/Subsystem.h"
#include "WPILib.h"

/**
 *
 *
 * @author ExampleAuthor
 */
typedef struct
{
	uint8_t tote1 : 1;
	uint8_t tote2 : 1;
	uint8_t tote3 : 1;
	uint8_t tote4 : 1;
	uint8_t tote5 : 1;
	uint8_t bin : 1;
	uint8_t checksum : 1;
	uint8_t padding : 1;
} packet_t;

typedef struct
{
	uint16_t new_val : 12;
	uint8_t id : 5;
	uint8_t is_max : 1;
} defaults_packet_t;


class SerialSensor: public Subsystem {
private:
	// It's desirable that everything possible under private except
	// for methods that implement subsystem capabilities
	SerialPort* sPort;
	packet_t m_packet;
	//pdata_t pdata;

public:
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

	// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	SerialSensor();
	void InitDefaultCommand();
	void Update();
	bool ValidatePacket(packet_t* packet);
	packet_t* GetState();
	void RequestUpdate();

};

#endif
