// RobotBuilder Version: 1.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

#include "OI.h"
#include "SmartDashboard/SmartDashboard.h"

#include "Commands/Acquisition/ArmLower.h"
#include "Commands/Acquisition/ArmRaise.h"
#include "Commands/Shooter/Fire.h"
#include "Commands/Drive/JoystickAutoDrive.h"
#include "Commands/Drive/JoystickDrive.h"
#include "Commands/Acquisition/RollerSpin.h"
#include "Commands/Acquisition/RollerStop.h"
#include "Commands/Drive/ShiftHigh.h"
#include "Commands/Drive/ShiftLow.h"
#include "Commands/Ejection/ExtendKicker.h"
#include "Commands/Ejection/RetractKicker.h"
#include "Commands/EjectBall.h"
#include "Commands/BallToShooter.h"
#include "Commands/Vision/TurnLEDsOn.h"

OI::OI() {
	// Process operator interface input here.

	m_lStick = new Joystick(DRV_JOY_LEFT);
	m_rStick = new Joystick(DRV_JOY_RIGHT);
	m_cStick = new Joystick(RBT_JOY_CONTROLLER);
	
	// Right Joystick Buttons
	m_driveHighBtn = new JoystickButton(m_rStick, 1); // Trigger on the right stick
	m_driveMotorsForce = new JoystickButton(m_rStick, 2);
	m_driveAutoRangeFor = new JoystickButton(m_rStick, 3);
	
	// Left Joystick Buttons
	m_driveLowBtn = new JoystickButton(m_lStick, 1);
	m_driveAutoRangeBack = new JoystickButton(m_lStick, 3);
	
	// Controller Joystick Buttons 1-5
	m_shootGoalBtn = new JoystickButton(m_cStick, 1);
	m_ejectBtn = new JoystickButton(m_cStick, 2);
	m_acquisitionToShooterBtn = new JoystickButton(m_cStick, 3);
	m_acquisitionInBtn = new JoystickButton(m_cStick, 4);
	m_acquisitionOutBtn = new JoystickButton(m_cStick, 5);
	
	// Controller Joystick Buttons 6-11
	m_armUpBtn = new JoystickButton(m_cStick, 6);
	m_armDownBtn = new JoystickButton(m_cStick, 7);
	m_shootTrussBtn = new JoystickButton(m_cStick, 8);
	m_shootShortBtn = new JoystickButton(m_cStick, 9);
	m_shooterOverride = new JoystickButton(m_cStick, 10);
	m_LEDBtn = new JoystickButton(m_cStick, 11);
	
	// Separation comment to make it easier to read

	// Right Joystick
	m_driveHighBtn->WhenPressed(new ShiftHigh());
	
	// Left Joystick
	m_driveLowBtn->WhenPressed(new ShiftLow());
	
	// Controller Joystick
    m_shootGoalBtn->WhenPressed(new Fire(SHO_DEFAULT_GOAL, true));
    m_ejectBtn->WhileHeld(new EjectBall());
    m_acquisitionToShooterBtn->WhenPressed(new BallToShooter());
    m_acquisitionInBtn->WhileHeld(new RollerSpin(false, true));
    m_acquisitionOutBtn->WhileHeld(new RollerSpin(true, false));
    
    m_armUpBtn->WhenPressed(new ArmRaise());
    m_armDownBtn->WhenPressed(new ArmLower());
    m_shootTrussBtn->WhenPressed(new Fire(SHO_DEFAULT_TRUSS, true));
    m_shootShortBtn->WhenPressed(new Fire(SHO_DEFAULT_SHORT, true));
	m_LEDBtn->ToggleWhenPressed(new TurnLEDsOn());
}

double OI::GetYLeft() {
	if(m_lStick->GetY() > -.03 && m_lStick->GetY() < .03) return 0; // Add a deadzone to the joystick
	else return m_lStick->GetY();
}

double OI::GetYRight() {
	if(m_rStick->GetY() > -.03 && m_rStick->GetY() < .03) return 0; // Add a deadzone to the joystick
	else return m_rStick->GetY();}

bool OI::IsReversed() {
	return 0;
}

bool OI::IsAutoRangeForwards() {
	return m_driveAutoRangeFor->Get();
}

bool OI::IsAutoRangeBackwards() {
	return m_driveAutoRangeBack->Get();
}

bool OI::AreMotorsForced() {
//	return true;
	return m_driveMotorsForce->Get();
}

bool OI::OverrideShooter() {
	return m_shooterOverride->Get();
}
