// RobotBuilder Version: 1.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.


#include "OI.h"

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES
#include "SmartDashboard/SmartDashboard.h"
#include "Commands/ArmLower.h"
#include "Commands/ArmRaise.h"
#include "Commands/AutonomousCommand.h"
#include "Commands/Fire.h"
#include "Commands/JoystickAutoDrive.h"
#include "Commands/JoystickDrive.h"
#include "Commands/RollerReverse.h"
#include "Commands/RollerSpin.h"
#include "Commands/RollerStop.h"
#include "Commands/ShiftHigh.h"
#include "Commands/ShiftLow.h"

// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES

OI::OI() {
	// Process operator interface input here.
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS

	m_rStick = new Joystick(2);
	
	m_driveHighBtn = new JoystickButton(m_rStick, 1);
	m_driveHighBtn->WhenPressed(new ShiftHigh());
	m_lStick = new Joystick(1);
	
	m_driveLowBtn = new JoystickButton(m_lStick, 1);
	m_driveLowBtn->WhenPressed(new ShiftLow());
     

        // SmartDashboard Buttons
	SmartDashboard::PutData("Autonomous Command", new AutonomousCommand());

	SmartDashboard::PutData("JoystickDrive", new JoystickDrive());

	SmartDashboard::PutData("JoystickAutoDrive", new JoystickAutoDrive());

	SmartDashboard::PutData("ShiftHigh", new ShiftHigh());

	SmartDashboard::PutData("ShiftLow", new ShiftLow());

	SmartDashboard::PutData("Fire", new Fire());

	SmartDashboard::PutData("RollerSpin", new RollerSpin());

	SmartDashboard::PutData("RollerReverse", new RollerReverse());

	SmartDashboard::PutData("RollerStop", new RollerStop());

	SmartDashboard::PutData("ArmRaise", new ArmRaise());

	SmartDashboard::PutData("ArmLower", new ArmLower());

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
}

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS

Joystick* OI::getm_rStick() {
	return m_rStick;
}

Joystick* OI::getm_lStick() {
	return m_lStick;
}

// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS
