// RobotBuilder Version: 1.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.


#include "RobotMap.h"
#include "LiveWindow/LiveWindow.h"


// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=ALLOCATION
CANJaguar* RobotMap::driveleft1 = NULL;
CANJaguar* RobotMap::driveleft2 = NULL;
CANJaguar* RobotMap::driveleft3 = NULL;
CANJaguar* RobotMap::driveright1 = NULL;
CANJaguar* RobotMap::driveright2 = NULL;
CANJaguar* RobotMap::driveright3 = NULL;
Solenoid* RobotMap::driveshift = NULL;
Solenoid* RobotMap::shooterleft = NULL;
Solenoid* RobotMap::shooterright = NULL;
DigitalInput* RobotMap::acquisitionballSensor = NULL;
SpeedController* RobotMap::acquisitionroller = NULL;
Solenoid* RobotMap::acquisitionraise = NULL;
// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=ALLOCATION

void RobotMap::init() {
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
	LiveWindow* lw = LiveWindow::GetInstance();

	driveleft1 = new CANJaguar(2);
	
	
	driveleft2 = new CANJaguar(3);
	
	
	driveleft3 = new CANJaguar(4);
	
	
	driveright1 = new CANJaguar(5);
	
	
	driveright2 = new CANJaguar(6);
	
	
	driveright3 = new CANJaguar(7);
	
	
	driveshift = new Solenoid(1, 1);
	lw->AddActuator("Drive", "shift", driveshift);
	
	shooterleft = new Solenoid(1, 2);
	lw->AddActuator("Shooter", "left", shooterleft);
	
	shooterright = new Solenoid(1, 3);
	lw->AddActuator("Shooter", "right", shooterright);
	
	acquisitionballSensor = new DigitalInput(1, 2);
	lw->AddSensor("Acquisition", "ballSensor", acquisitionballSensor);
	
	acquisitionroller = new Victor(1, 1);
	lw->AddActuator("Acquisition", "roller", (Victor*) acquisitionroller);
	
	acquisitionraise = new Solenoid(1, 4);
	lw->AddActuator("Acquisition", "raise", acquisitionraise);
	

	// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
}
