// RobotBuilder Version: 0.0.2
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

#include "OI.h"
#include "SmartDashboard/SmartDashboard.h"
#include "Commands/AutonomousCommand.h"
#include "Commands/Arm/ArmPosition.h"
#include "Commands/Arm/ArmUserPosition.h"
#include "Commands/Drive/JoystickDrive.h"
#include "Commands/Drive/JoystickAutoDrive.h"
#include "Commands/Drive/ShiftHigh.h"
#include "Commands/Drive/ShiftLow.h"
#include "Commands/Shooter/ShooterShoot.h"
#include "Commands/Shooter/ShooterSpin.h"
#include "Commands/Shooter/ShooterStop.h"
#include "Commands/Shooter/ShootOnce.h"

OI::OI() {
	// Process operator interface input here.
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
	m_lStick = new Joystick(DRV_JOY_LEFT);
	m_rStick = new Joystick(DRV_JOY_RIGHT);
     
        // SmartDashboard Buttons
	SmartDashboard::PutData("Autonomous Command", new AutonomousCommand());
	// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS

	m_shootBtn = new DigitalIOButton(1);
	m_shooterManualBtn = new DigitalIOButton(2);
	m_shooterDefaultBtn = new DigitalIOButton(3);

	m_armStowBtn = new DigitalIOButton(4);
	m_armFeederBtn = new DigitalIOButton(5);
	m_armMiddleBtn = new DigitalIOButton(6);
	m_armPyramidBtn = new DigitalIOButton(7);
	m_armTopBtn = new DigitalIOButton(8);
	
	m_shootBtn->WhileHeld(new ShooterShoot());
	m_shootBtn->WhenReleased(new ShootOnce());
	m_shooterManualBtn->WhileHeld(new ShooterSpin(true));
	m_shooterDefaultBtn->WhileHeld(new ShooterSpin(false));
	
	// PLACEHOLDER CONSTANTS! REPLACE WITH PROPER VALUES LATER!!!!!!!!
	m_armStowBtn->WhenPressed(new ArmPosition(1, 1));
	m_armFeederBtn->WhenPressed(new ArmPosition(2, 2));
	m_armMiddleBtn->WhenPressed(new ArmPosition(3, 3));
	m_armPyramidBtn->WhenPressed(new ArmPosition(4, 4));
	m_armTopBtn->WhenPressed(new ArmPosition(5, 5));
}

double OI::GetYLeft() {
	return m_lStick->GetY();
}

double OI::GetYRight() {
	return m_rStick->GetY();
}

double OI::GetWristSetpoint()
{
	// Pending SmartDashboard input
	return 42.0;
}



double OI::GetElbowSetpoint()
{
	// Pending SmartDashboard input
	return 900.1;
}



double OI::GetShooterSpeed()
{
	return DriverStation::GetInstance()->GetEnhancedIO().GetAnalogIn(1);
}


