// RobotBuilder Version: 0.0.2
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

#include "Robot.h"
#include "Commands/TwoDiscAuton.h"

#include "Robot.h"
OI* Robot::oi = 0;
Shooter* Robot::shooter = 0;
Arm* Robot::arm = 0;
Drive* Robot::drive = 0;
Loader* Robot::loader = 0;
void Robot::RobotInit() {
	RobotMap::init();
	shooter = new Shooter();
	arm = new Arm();
	drive = new Drive();
	loader = new Loader();
	// This MUST be here. If the OI creates Commands (which it very likely
	// will), constructing it during the construction of CommandBase (from
	// which commands extend), subsystems are not guaranteed to be
	// yet. Thus, their requires() statements may grab null pointers. Bad
	// news. Don't move it.
	comp = new Compressor(1,1);
	comp->Start();
	oi = new OI();
	lw = LiveWindow::GetInstance();
	// instantiate the command used for the autonomous period
	autonomousCommand = new TwoDiscAuton();
  }
	
void Robot::AutonomousInit() {
	Scheduler::GetInstance()->Run();
	if (autonomousCommand != NULL)
		autonomousCommand->Start();
}
	
void Robot::AutonomousPeriodic() {
	Scheduler::GetInstance()->Run();
}
	
void Robot::TeleopInit() {
	// This makes sure that the autonomous stops running when
	// teleop starts running. If you want the autonomous to 
	// continue until interrupted by another command, remove
	// this line or comment it out.
	autonomousCommand->Cancel();
}
	
void Robot::TeleopPeriodic() {
//	if (autonomousCommand != NULL)
		Scheduler::GetInstance()->Run();
}
void Robot::TestPeriodic() {
	lw->Run();
	
}
START_ROBOT_CLASS(Robot);
