// RobotBuilder Version: 0.0.2
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.
#include "RobotMap.h"
#include "LiveWindow/LiveWindow.h"
// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=ALLOCATION
CANJaguar* RobotMap::shooterSpinner = NULL;
Servo* RobotMap::shooterConveyor = NULL;
DigitalInput* RobotMap::shooterExit = NULL;
CANJaguar* RobotMap::armWrist = NULL;
CANJaguar* RobotMap::armElbow = NULL;
SpeedController* RobotMap::driveLeft = NULL;
SpeedController* RobotMap::driveRight = NULL;
Encoder* RobotMap::drivelEnc = NULL;
Encoder* RobotMap::driverEnc = NULL;
Solenoid* RobotMap::driveShift = NULL;
Solenoid* RobotMap::climberHook = NULL;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=ALLOCATION
void RobotMap::init() {
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
	LiveWindow* lw = LiveWindow::GetInstance();
	shooterSpinner = new CANJaguar(4);
	
	
	shooterConveyor = new Servo(1, 1);
	lw->AddActuator("Shooter", "Conveyor", shooterConveyor);
	
	shooterExit = new DigitalInput(1, 1);
	lw->AddSensor("Shooter", "Exit", shooterExit);
	
	armWrist = new CANJaguar(2);
	
	
	armElbow = new CANJaguar(3);
	
	
	driveLeft = new Victor(1, 2);
	lw->AddActuator("Drive", "Left", (Victor*) driveLeft);
	
	driveRight = new Victor(1, 3);
	lw->AddActuator("Drive", "Right", (Victor*) driveRight);
	
	drivelEnc = new Encoder(1, 2, 1, 3, false, Encoder::k4X);
	lw->AddSensor("Drive", "lEnc", drivelEnc);
	drivelEnc->SetDistancePerPulse(1.0);
        drivelEnc->SetPIDSourceParameter(Encoder::kRate);
        drivelEnc->Start();
	driverEnc = new Encoder(1, 4, 1, 5, false, Encoder::k4X);
	lw->AddSensor("Drive", "rEnc", driverEnc);
	driverEnc->SetDistancePerPulse(1.0);
        driverEnc->SetPIDSourceParameter(Encoder::kRate);
        driverEnc->Start();
	driveShift = new Solenoid(1, 1);
	lw->AddActuator("Drive", "Shift", driveShift);
	
	climberHook = new Solenoid(1, 2);
	lw->AddActuator("Climber", "Hook", climberHook);
	
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
}
