// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "OI.h"

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES
#include "SmartDashboard/SmartDashboard.h"
#include "Commands/Drive/AutoDrive.h"
#include "Commands/AutonomousCommand.h"
#include "Commands/Drive/JoystickDrive.h"


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES

OI::OI() {
    // Process operator interface input here.
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    rStick.reset(new Joystick(1));
    
    lStick.reset(new Joystick(0));
    

    // SmartDashboard Buttons

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
}

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS

//std::shared_ptr<Joystick> OI::getlStick() {
//   return lStick;
//}
//
//std::shared_ptr<Joystick> OI::getrStick() {
//   return rStick;
//}

double OI::GetYRight() {
	double value = rStick->GetY();
	if(fabs(value) > .01) {
		return value;
	}
	return 0;
}

double OI::GetYLeft() {
	double value = lStick->GetY();
	if(fabs(value) > .01) {
		return value;
	}
	return 0;
}


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS
