// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "RobotMap.h"
#include "LiveWindow/LiveWindow.h"


// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=ALLOCATION
std::shared_ptr<Victor> RobotMap::drivelDrive1;
std::shared_ptr<Victor> RobotMap::drivelDrive2;
std::shared_ptr<Victor> RobotMap::driverDrive1;
std::shared_ptr<Victor> RobotMap::driverDrive2;
//Victor* RobotMap::drivelDrive1 = NULL;
//Victor* RobotMap::drivelDrive2 = NULL;
//Victor* RobotMap::driverDrive1 = NULL;
//Victor* RobotMap::driverDrive2 = NULL;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=ALLOCATION

void RobotMap::init() {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    LiveWindow *lw = LiveWindow::GetInstance();

    drivelDrive1.reset(new Victor(2));
    lw->AddActuator("Drive", "lDrive1", (Victor&) drivelDrive1);
    
    drivelDrive2.reset(new Victor(3));
    lw->AddActuator("Drive", "lDrive2", (Victor&) drivelDrive2);
    
    driverDrive1.reset(new Victor(0));
    lw->AddActuator("Drive", "rDrive1", (Victor&) driverDrive1);
    
    driverDrive2.reset(new Victor(1));
    lw->AddActuator("Drive", "rDrive2", (Victor&) driverDrive2);
    


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
}
