// RobotBuilder Version: 1.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

#include "Fire.h"
#include "../Ejection/ExtendKicker.h"

Fire::Fire(double fireLength, bool checkOverride):
		m_fireLength(fireLength),
		m_checkOverride(checkOverride)
{
	// Use requires() here to declare subsystem dependencies
	// eg. requires(chassis);
	Requires(Robot::shooter);
}

// Called just before this Command runs the first time
void Fire::Initialize() {
	shootTime.Start();
	shootTime.Reset();
	m_dryFire = false;
	if(!m_checkOverride && // Being told to check the override command
			!Robot::acquisition->BallReady() &&  // Ball isn't in the shooter 
			!Robot::oi->OverrideShooter()) // And not being told to override
	{
		m_dryFire = true; // Do not fire
	}
}

// Called repeatedly when this Command is scheduled to run
void Fire::Execute() {
	if(m_fireLength <= 0 || m_dryFire)
	{
		Robot::shooter->SetSolenoids(false);
	}
	else if(shootTime.Get() < m_fireLength)
	{
		Robot::shooter->SetSolenoids(true);
	}
	else
	{
		Robot::shooter->SetSolenoids(false);
	}
}

// Make this return true when this Command no longer needs to run execute()
bool Fire::IsFinished() {
	return shootTime.Get() > m_fireLength;
}

// Called once after isFinished returns true
void Fire::End() {
	
}

// Called when another command which requires one or more of the same
// subsystems is scheduled to run
void Fire::Interrupted() {
	
}
