// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#ifndef PROCESSACCEL_H
#define PROCESSACCEL_H
#include "Commands/Subsystem.h"
#include "WPILib.h"

/**
 *
 *
 * @author ExampleAuthor
 */
typedef struct
{
	uint8_t chksum : 1;
	uint8_t bin : 1;
	uint8_t tote5 : 1;
	uint8_t tote4 : 1;
	uint8_t tote3 : 1;
	uint8_t tote2 : 1;
	uint8_t tote1 : 1;
	uint8_t padding : 1;
} packet_t __attribute((packed));


class ProcessAccel: public Subsystem {
private:
	// It's desirable that everything possible under private except
	// for methods that implement subsystem capabilities
	SerialPort* sPort;
	packet_t* packet;
	//pdata_t pdata;

public:
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

	// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	ProcessAccel();
	void InitDefaultCommand();
	void readByte();
	void writeByte(const char* byte);
	bool checkStatus();
	packet_t* getData();

};

#endif
